### ISSUE TITLE
Hitting crashes

### ISSUE THREAD

**Issue by jkugler** [ragestack/blockchain-parser#12]
Hello! Is this meant to be run under Python 2 or 3? Under Python 2, I get:
```
Start /var/bitcoin/data/blocks/blk00000.dat in 2020-02-26 11:04:09.093834
Traceback (most recent call last):
  File "./blockchain-parser.py", line 79, in <module>
    tmpHex = read_bytes(f,4)
  File "./blockchain-parser.py", line 38, in read_bytes
    data = data.hex().upper()
AttributeError: 'str' object has no attribute 'hex'
```
Under Python 3 I get:
```
Start /var/bitcoin/data/blocks/blk00000.dat in 2020-02-26 11:05:58.985973
Traceback (most recent call last):
  File "./blockchain-parser.py", line 169, in <module>
    tmpHex = read_bytes(f,scriptLength,'B')
  File "./blockchain-parser.py", line 35, in read_bytes
    data = file.read(n)
MemoryError
```
I'm using data files from bitcoin-core 0.19.  Seems similar to issue #3

**Comment by jkugler** [comment]
I added this: `print("Going to read %s bytes" % n)` right before line 35 (under python3) and got this:
```
Start /var/bitcoin/data/blocks/blk00000.dat in 2020-02-26 11:46:47.214393
Going to read 4 bytes
Going to read 4 bytes
Going to read 80 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 77 bytes
Going to read 4 bytes
Going to read 8 bytes
Going to read 67 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 80 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 7 bytes
Going to read 4 bytes
Going to read 8 bytes
Going to read 67 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 0 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 0 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 0 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 195 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 162 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 178 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 124 bytes
Going to read 4 bytes
Going to read 32 bytes
Going to read 4 bytes
Going to read 327680000000511 bytes
Traceback (most recent call last):
  File "./blockchain-parser.py", line 170, in <module>
    tmpHex = read_bytes(f,scriptLength,'B')
  File "./blockchain-parser.py", line 36, in read_bytes
    data = file.read(n)
MemoryError
```
Where is it getting its values to read? :)

**Comment by ragestack** [comment]
May be the dat file was not fully downloaded. My script works with the dat files that has correct raw blocks in it. Try to not stop loading files from bitcoin network and check for complete loading of the file you try to parse.

**Comment by jkugler** [comment]
The client says it has fully synced. I think I let it do its sync all in one go. Maybe not?

**Comment by ragestack** [comment]
You can upload somewhere your dat file and give me the link, I check it by myself. I think there is a data corruption, till now my script works perfectly.

**Comment by jkugler** [comment]
Not sure it's worth uploading 200+ GB somewhere, but thanks for the offer. I'll see what other paths I have.

**Comment by ragestack** [comment]
I'am not about the whole blockchain, i'am about one of those dat files that you could not parse.

**Comment by jkugler** [comment]
Ah! I'll see if I still have it around.
