### ISSUE TITLE
MemoryError after first block is parsed

### ISSUE THREAD

**Issue by Ziggy644** [ragestack/blockchain-parser#27]
Traceback (most recent call last):
  File "D:\parser\blockchain-parser.py", line 167, in <module>
    tmpHex = read_bytes(f,scriptLength,'B')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\parser\blockchain-parser.py", line 33, in read_bytes
    data = file.read(n)
           ^^^^^^^^^^^^
MemoryError

**Comment by ragestack** [comment]
You trying to parse Bitcoin data or may be some altcoin?

**Comment by Ziggy644** [comment]
No, just Bitcoin. It also seems to happen at other blocks indexes.

**Comment by ragestack** [comment]
Can you share this binary blk file? I try to check

**Comment by Ziggy644** [comment]
I figured out the issue myself; I'm using an older Bitcoin-qt version (0.14.3). Because of this, the script sometimes returns an incorrect tx input script size (over 10GB) which causes Python to return a MemoryError. I'm not sure this happens with the newest version of Bitcoin-qt.

**Comment by ragestack** [comment]
Bitcoin-QT version does not matter, sometimes all versions add to the binary data 1 strange 00 byte, that not documented anywhere
